module.exports = {
  icons: {
    die:       require('./assets/images/icons/icons_die.png'),
    cards:     require('./assets/images/icons/icons_cards.png'),
    coins:     require('./assets/images/icons/icons_coins.png'),
    eightBall: require('./assets/images/icons/icons_eight-ball.png'),
    bottle:    require('./assets/images/icons/icons_bottle.png'),
    straws:    require('./assets/images/icons/icons_straws.png'),
    rps:       require('./assets/images/icons/icons_rps.png'),
    roulette:  require('./assets/images/icons/icons_roulette.png'),
    wheel:     require('./assets/images/icons/icons_wheel.png'),
    number:    require('./assets/images/icons/icons_number.png'),
    cups:      require('./assets/images/icons/icons_cups.png'),
    russianRoulette: require('./assets/images/icons/icons_russian-roulette.png'),
  },
  die: [
    require('./assets/images/die/die-01.png'),
    require('./assets/images/die/die-02.png'),
    require('./assets/images/die/die-03.png'),
    require('./assets/images/die/die-04.png'),
    require('./assets/images/die/die-05.png'),
    require('./assets/images/die/die-06.png'),
  ],
  cards: [
    [
      require('./assets/images/cards/cards_spade-01.png'),
      require('./assets/images/cards/cards_spade-02.png'),
      require('./assets/images/cards/cards_spade-03.png'),
      require('./assets/images/cards/cards_spade-04.png'),
      require('./assets/images/cards/cards_spade-05.png'),
      require('./assets/images/cards/cards_spade-06.png'),
      require('./assets/images/cards/cards_spade-07.png'),
      require('./assets/images/cards/cards_spade-08.png'),
      require('./assets/images/cards/cards_spade-09.png'),
      require('./assets/images/cards/cards_spade-10.png'),
      require('./assets/images/cards/cards_spade-11.png'),
      require('./assets/images/cards/cards_spade-12.png'),
      require('./assets/images/cards/cards_spade-13.png'),
    ],
    [
      require('./assets/images/cards/cards_clubs-01.png'),
      require('./assets/images/cards/cards_clubs-02.png'),
      require('./assets/images/cards/cards_clubs-03.png'),
      require('./assets/images/cards/cards_clubs-04.png'),
      require('./assets/images/cards/cards_clubs-05.png'),
      require('./assets/images/cards/cards_clubs-06.png'),
      require('./assets/images/cards/cards_clubs-07.png'),
      require('./assets/images/cards/cards_clubs-08.png'),
      require('./assets/images/cards/cards_clubs-09.png'),
      require('./assets/images/cards/cards_clubs-10.png'),
      require('./assets/images/cards/cards_clubs-11.png'),
      require('./assets/images/cards/cards_clubs-12.png'),
      require('./assets/images/cards/cards_clubs-13.png'),
    ],
    [
      require('./assets/images/cards/cards_hearts-01.png'),
      require('./assets/images/cards/cards_hearts-02.png'),
      require('./assets/images/cards/cards_hearts-03.png'),
      require('./assets/images/cards/cards_hearts-04.png'),
      require('./assets/images/cards/cards_hearts-05.png'),
      require('./assets/images/cards/cards_hearts-06.png'),
      require('./assets/images/cards/cards_hearts-07.png'),
      require('./assets/images/cards/cards_hearts-08.png'),
      require('./assets/images/cards/cards_hearts-09.png'),
      require('./assets/images/cards/cards_hearts-10.png'),
      require('./assets/images/cards/cards_hearts-11.png'),
      require('./assets/images/cards/cards_hearts-12.png'),
      require('./assets/images/cards/cards_hearts-13.png'),
    ],
    [
      require('./assets/images/cards/cards_diamonds-01.png'),
      require('./assets/images/cards/cards_diamonds-02.png'),
      require('./assets/images/cards/cards_diamonds-03.png'),
      require('./assets/images/cards/cards_diamonds-04.png'),
      require('./assets/images/cards/cards_diamonds-05.png'),
      require('./assets/images/cards/cards_diamonds-06.png'),
      require('./assets/images/cards/cards_diamonds-07.png'),
      require('./assets/images/cards/cards_diamonds-08.png'),
      require('./assets/images/cards/cards_diamonds-09.png'),
      require('./assets/images/cards/cards_diamonds-10.png'),
      require('./assets/images/cards/cards_diamonds-11.png'),
      require('./assets/images/cards/cards_diamonds-12.png'),
      require('./assets/images/cards/cards_diamonds-13.png'),
    ],
  ],
  coins: [
    require('./assets/images/coins/coins_tails.png'),
    require('./assets/images/coins/coins_heads.png'),
  ],
  eightBall: [
    require('./assets/images/eight-ball/eight-ball-01.png'),
    require('./assets/images/eight-ball/eight-ball-02.png'),
    require('./assets/images/eight-ball/eight-ball-03.png'),
    require('./assets/images/eight-ball/eight-ball-04.png'),
    require('./assets/images/eight-ball/eight-ball-05.png'),
    require('./assets/images/eight-ball/eight-ball-06.png'),
    require('./assets/images/eight-ball/eight-ball-07.png'),
    require('./assets/images/eight-ball/eight-ball-08.png'),
    require('./assets/images/eight-ball/eight-ball-09.png'),
    require('./assets/images/eight-ball/eight-ball-10.png'),
    require('./assets/images/eight-ball/eight-ball-11.png'),
    require('./assets/images/eight-ball/eight-ball-12.png'),
  ],
  bottle: require('./assets/images/bottle/bottle.png'),
  rps: [
    require('./assets/images/rps/rps_rock.png'),
    require('./assets/images/rps/rps_paper.png'),
    require('./assets/images/rps/rps_scissors.png'),
  ],
  roulette: require('./assets/images/roulette/roulette.png'),
  wheel: require('./assets/images/wheel/wheel.png'),
  cup: require('./assets/images/cups/cup.png'),
  russianRoulette: require('./assets/images/russian-roulette/russian-roulette.png'),
}